name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19.x, 1.20.x, 1.21.x, 1.22.x, 1.23.x]

    services:
      dicedb:
        image: dicedb/dicedb:latest
        ports:
          - "7379:7379"

    steps:
      - name: Set up ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: make dicedbtest
